const workbenchRules = {
    "workbenchColorCustomizations": {
      "activityBar.background": "",
      "activityBar.foreground": "",
      "activityBarBadge.background": "",
      "activityBarBadge.foreground": "",
      "badge.background": "",
      "button.background": "",
      "debugToolBar.background": "",
      "dropdown.background": "",
      "diffEditor.insertedTextBackground": "",
      "dropdown.border": "",
      "editor.background": "",
      "editorError.foreground": "",
      "editorIndentGuide.activeBackground": "",
      "editorMarkerNavigation.background": "",
      "editorRuler.foreground": "",
      "editor.lineHighlightBackground": "",
      "editor.selectionBackground": "",
      "editor.selectionHighlightBackground": "",
      "editor.selectionHighlightBorder": "",
      "editorCursor.background": "",
      "editorCursor.foreground": "",
      "editorBracketMatch.border": "",
      "editorBracketMatch.background": "",
      "editor.findMatchBackground": "",
      "editor.findMatchBorder": "",
      "editor.findMatchHighlightBackground": "",
      "editor.wordHighlightBackground": "",
      "editor.wordHighlightBorder": "",
      "editor.wordHighlightStrongBackground": "26",
      "editor.wordHighlightStrongBorder": "",
      "editorGroup.background": "",
      "editorGroup.border": "",
      "editorGroupHeader.tabsBackground": "",
      "editorIndentGuide.background": "",
      "editorLineNumber.foreground": "",
      "editorActiveLineNumber.foreground": "",
      "editorWhitespace.foreground": "",
      "editorHoverWidget.background": "",
      "editorHoverWidget.border": "",
      "editorSuggestWidget.background": "",
      "editorSuggestWidget.border": "",
      "editorSuggestWidget.selectedBackground": "",
      "editorWidget.background": "",
      "focusBorder": "",
      "input.background": "",
      "list.activeSelectionBackground": "",
      "list.activeSelectionForeground": "",
      "list.focusBackground": "",
      "list.hoverBackground": "",
      "list.highlightForeground": "",
      "list.inactiveSelectionBackground": "",
      "list.inactiveSelectionForeground": "",
      "peekViewEditor.matchHighlightBackground": "",
      "scrollbarSlider.background": "",
      "scrollbarSlider.activeBackground": "",
      "scrollbarSlider.hoverBackground": "",
      "sideBar.background": "",
      "sideBarSectionHeader.background": "",
      "statusBar.background": "",
      "statusBar.foreground": "",
      "statusBarItem.hoverBackground": "",
      "statusBar.noFolderBackground": "",
      "statusBar.debuggingBackground": "",
      "statusBar.debuggingBorder": "",
      "statusBar.debuggingForeground": "",
      "tab.activeBackground": "",
      "tab.border": "",
      "tab.inactiveBackground": "",
      "tab.hoverBackground": "",
      "tab.unfocusedHoverBackground": "",
      "terminal.foreground": "",
      "terminal.ansiBlack": "",
      "terminal.ansiBlue": "",
      "terminal.ansiGreen": "",
      "terminal.ansiYellow": "",
      "titleBar.activeBackground": "",
      "titleBar.activeForeground": "",
      "titleBar.inactiveBackground": "",
      "titleBar.inactiveForeground": ""
    }
}

const tokenRules = {
    "editorTokenColorCustomizations": {
        "comments": "",
        "functions": "",
        "keywords": "",
        "numbers": "",
        "strings": "",
        "textMateRules": "",
        "types": "",
        "variables": ""
    }
}

export {workbenchRules, tokenRules};